<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_receiptno</name>
   <tag></tag>
   <elementGuidId>817afc6b-b133-47e1-9b3b-e7bedbc492dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;receiptno0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Medical/ApplyMedical/medical_table</value>
      <webElementGuid>79370c29-e3ff-46ef-a062-d766be990350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c946408d-1242-4965-b977-b11291a71362</webElementGuid>
   </webElementProperties>
</WebElementEntity>
