<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lookup</name>
   <tag></tag>
   <elementGuidId>bb3b104f-2d50-4e18-9806-ab8f0a2f83f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lookupclinic20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lookupclinic20']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>80375067-557d-43a1-be0b-716978cd3e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>lu_leaveclinicpaneless_newgui.jsp?ispanel=0&amp;code=nonpanelclinicname0&amp;desc=nonpanelclinicdesc0&amp;code2=address0&amp;code3=gstcompanyno0&amp;code5=isgovernment0</value>
      <webElementGuid>d6332a3e-af78-401a-bd68-0c9d2cc315ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookupclinic20</value>
      <webElementGuid>0bfa7360-2b07-468a-a1c5-7c02a3ea9474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hr-entry-lookup </value>
      <webElementGuid>1e3ec33c-5bf2-4d9b-a79f-15d79bb8db2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b763f700-73b5-472a-90f9-f77399a88154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lookup</value>
      <webElementGuid>3c1bff05-b573-489a-9292-0ad58c0d2a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lookup</value>
      <webElementGuid>bf36e931-6e4a-47ff-9302-859033561051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookupclinic20&quot;)</value>
      <webElementGuid>a13c1779-20af-48a9-a448-d2ebde07cac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Medical/Page_- Employee Self Service/frame_concat(body bgcolor, , FFFFFF, ,  tex_1268c1</value>
      <webElementGuid>eab269fa-d0a5-45b4-b1bb-ed1eb1b53cb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lookupclinic20']</value>
      <webElementGuid>1110c5bb-d324-450f-8e86-7071ce99884e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trhird_0']/td[3]/div/a[2]</value>
      <webElementGuid>221bdb15-1fc9-45fd-9d30-30aefc577db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lookup'])[1]/following::a[1]</value>
      <webElementGuid>101ee4a0-b245-4c42-b396-007d288e3057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non Panel Clinic / Non Panel Hospital Name'])[1]/following::a[2]</value>
      <webElementGuid>48eed71b-e061-475b-a43c-964621bd8384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason Visit Non Panel'])[1]/preceding::a[1]</value>
      <webElementGuid>ce574022-3d1f-47ba-9c9b-434447a7e7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'lu_leaveclinicpaneless_newgui.jsp?ispanel=0&amp;code=nonpanelclinicname0&amp;desc=nonpanelclinicdesc0&amp;code2=address0&amp;code3=gstcompanyno0&amp;code5=isgovernment0')]</value>
      <webElementGuid>fc7ab39c-e837-42fb-a597-8016156b0e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a[2]</value>
      <webElementGuid>b8cff9ea-600f-4856-b288-d4e63a3d759c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'lu_leaveclinicpaneless_newgui.jsp?ispanel=0&amp;code=nonpanelclinicname0&amp;desc=nonpanelclinicdesc0&amp;code2=address0&amp;code3=gstcompanyno0&amp;code5=isgovernment0' and @id = 'lookupclinic20' and @title = 'Lookup' and (text() = 'Lookup' or . = 'Lookup')]</value>
      <webElementGuid>65fda17c-c45e-4bd4-8496-8d294584a088</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
