<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lookup_1</name>
   <tag></tag>
   <elementGuidId>26ad811c-9fd3-4f81-bfe6-f8ff08390b11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lookupillness0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lookupillness0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9717821-7b61-4bc1-8f9f-dfc30fd02299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>lu_illnessClaim_newgui.jsp?code=illcode0&amp;desc=illname0</value>
      <webElementGuid>c9c30703-651c-4b5d-b916-ff73d9501951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookupillness0</value>
      <webElementGuid>08ee6d46-6826-49b4-aacf-e5e68adc0a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hr-entry-lookup lastRow</value>
      <webElementGuid>fdbd7019-73c9-4368-9d2d-43549455829f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4c24dc78-cadd-4872-b99f-fc224092d67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lookup</value>
      <webElementGuid>a04e80e5-7bcd-4ff2-8533-68237e8c94f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lookup</value>
      <webElementGuid>21823a22-e4a2-4cb6-86ac-e04e175b826e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookupillness0&quot;)</value>
      <webElementGuid>9c8a620c-4e8b-4f30-9cac-3751371e8f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Medical/Page_- Employee Self Service/frame_concat(body bgcolor, , FFFFFF, ,  tex_1268c1</value>
      <webElementGuid>ba3ff0f1-3db2-4913-8b21-0df8b4c2a081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lookupillness0']</value>
      <webElementGuid>2ee1268c-849b-4c57-a852-9fc66e0c8013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trfouth_0']/td[3]/div/a</value>
      <webElementGuid>40b94897-c2ba-4158-9015-4bc3064c063c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Illness Type'])[1]/following::a[1]</value>
      <webElementGuid>4f84d01f-bfc0-482a-beb4-3c72098ec61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select date'])[3]/following::a[1]</value>
      <webElementGuid>b0ed0775-4794-44a3-b331-150e4fed812f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Illness Category'])[1]/preceding::a[1]</value>
      <webElementGuid>d287f18c-bab4-4170-8976-ce98490aa0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'lu_illnessClaim_newgui.jsp?code=illcode0&amp;desc=illname0')]</value>
      <webElementGuid>aec834df-2068-4b9e-9dac-3003506e05f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/div/a</value>
      <webElementGuid>a5f4f348-23c7-4b1c-a5d9-7c1c343b90c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'lu_illnessClaim_newgui.jsp?code=illcode0&amp;desc=illname0' and @id = 'lookupillness0' and @title = 'Lookup' and (text() = 'Lookup' or . = 'Lookup')]</value>
      <webElementGuid>b94dd88e-fa44-4359-b17e-38084f9690b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
