<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_concat(body bgcolor, , FFFFFF, ,  tex_1268c1</name>
   <tag></tag>
   <elementGuidId>f1c533eb-5996-4d2a-8e8b-4e4c702a49a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@id='content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>4e6f401c-9844-4b0a-bcd7-5f30d053f4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>eb0b7abf-c81b-4cdd-a05a-756c2b18f823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>19ad7898-72db-40bf-bddd-68bdcc5bca71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>dashboard_ess.jsp?mysessionid=20240503111303.730&amp;newdate=03/05/202411:13:03</value>
      <webElementGuid>f5431c60-ecef-48dc-be07-465079c58878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)</value>
      <webElementGuid>386c9ec8-2eb3-4b7f-8cf6-35a054b7535e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@id='content']</value>
      <webElementGuid>0cfd2f6f-4f32-4e45-b933-fd64bca705e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>6e86036b-3f61-43e3-a3c3-ee1886e200e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'content' and @id = 'content' and @src = 'dashboard_ess.jsp?mysessionid=20240503111303.730&amp;newdate=03/05/202411:13:03']</value>
      <webElementGuid>8139c47a-e676-4795-9150-02e221e6e48e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
