<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Discharge Date_dischargedate0</name>
   <tag></tag>
   <elementGuidId>178514c2-9d3f-4691-87a1-e1a08fb2e84f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dischargedate0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dischargedate0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ca6b496-ada7-417f-834d-144a2d49a3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b676a5ad-69c3-4219-ac82-fa0698e0fa1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dischargedate0</value>
      <webElementGuid>744064bf-48b6-4e98-89c5-fc7adbe13cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dischargedate0</value>
      <webElementGuid>ea4faf65-a437-4610-83e1-d6f02c2637d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hr-date hr-list-date-input checkDateRange hasDatepicker</value>
      <webElementGuid>76780573-f970-4e59-88cc-5d61480f5a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trfifth_0&quot;)/td[6]/div[@class=&quot;div_dischargedate0&quot;]/input[@id=&quot;dischargedate0&quot;]</value>
      <webElementGuid>f3e82fb3-86ed-43c8-b5aa-f26a6c4d861e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Medical/Page_- Employee Self Service/frame_concat(body bgcolor, , FFFFFF, ,  tex_1268c1</value>
      <webElementGuid>56bc1667-667e-4a28-8757-cf214eba89db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dischargedate0']</value>
      <webElementGuid>f98a60be-f554-4d4c-bc69-8e81beff8aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trfifth_0']/td[6]/div/input</value>
      <webElementGuid>e3d1aaf4-8254-413a-84f7-ffd3001d6f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]/div/input</value>
      <webElementGuid>9f28ed86-97a7-48ca-b9a9-e3eb339bb31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dischargedate0' and @id = 'dischargedate0']</value>
      <webElementGuid>f835946b-d894-4886-a449-0788d0b52e2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
