<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Receipt No_receiptno0</name>
   <tag></tag>
   <elementGuidId>c2cf8b23-8027-42a3-afc0-51c915f1c80b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#receiptno0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='receiptno0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7dbd81c7-9675-42c1-987f-bd849ead2c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5d129fb-b3ba-49bd-8cf2-5657e27094f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>receiptno0</value>
      <webElementGuid>afe35707-dbf3-4f59-b3b8-133d5abe8eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>receiptno0</value>
      <webElementGuid>2409a2b5-e580-48f2-9ebd-4a5ad416a6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hr-small </value>
      <webElementGuid>5893354d-ef58-4ea6-90c2-54e3a064a836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c0bcb727-782c-451b-a9bd-2d58b5ebe9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;receiptno0&quot;)</value>
      <webElementGuid>e7a25bd6-5458-460b-9669-3a8aac7a430b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Medical/Page_- Employee Self Service/frame_concat(body bgcolor, , FFFFFF, ,  tex_1268c1</value>
      <webElementGuid>41fd35c6-2c10-4b5a-b87e-47abc533cf14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='receiptno0']</value>
      <webElementGuid>d3934fad-0a0d-435e-b473-1b7b348842fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trhird_0']/td[8]/div/input</value>
      <webElementGuid>adc23076-16ab-405f-a286-a213c4537400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/input</value>
      <webElementGuid>1fa7df6e-fbd2-4e8b-8535-b6d78beee6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'receiptno0' and @id = 'receiptno0']</value>
      <webElementGuid>66d1ff85-f5fc-409d-a07d-a235d3f22e27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
