<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Attachment_btn-sendapprover</name>
   <tag></tag>
   <elementGuidId>45371819-a6e8-4bc7-b909-471a33415180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-sendapprover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn-sendapprover']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de17eb66-a624-43fe-9816-af4e260796c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3040b3b5-bde6-42f4-85f1-b0006cf3a695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-sendapprover</value>
      <webElementGuid>0003d187-bfa3-4860-9d6d-63f8cebea7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-sendapprover</value>
      <webElementGuid>556e8b81-7399-4bb2-8e46-3c3d29a8bf8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Send to approver</value>
      <webElementGuid>5c6d882f-a6ed-4164-be7b-ece0a7e4069a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hr-button</value>
      <webElementGuid>64b6ec11-fc11-46f0-be7e-2ca168db09e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-sendapprover&quot;)</value>
      <webElementGuid>d5df2de4-d2eb-4373-be6c-9f1113a46391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Medical/Page_- Employee Self Service/frame_concat(body bgcolor, , FFFFFF, ,  tex_1268c1</value>
      <webElementGuid>bef63267-9b9b-4986-ab6c-abb5cb00085c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn-sendapprover']</value>
      <webElementGuid>598d9c75-44c8-4de2-b4e1-6098e632838a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lyinfo']/div[7]/input[2]</value>
      <webElementGuid>34719388-c09a-4228-8f9c-51df9fdfb492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input[2]</value>
      <webElementGuid>de6f4e88-132d-49ff-a1bd-788dfb62477d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btn-sendapprover' and @id = 'btn-sendapprover']</value>
      <webElementGuid>d74da512-4ca5-40f9-bfff-7cb0da54cbb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
