<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Time Out (24 hours)_amtbfgst0</name>
   <tag></tag>
   <elementGuidId>3f5c0c27-4f00-46a5-b03c-fea594c043c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amtbfgst0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amtbfgst0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09a3ae2c-83e6-43e9-8f2c-4fa17c5faf07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0851b9e0-5ad1-4b74-8a67-4876856f680b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>amtbfgst0</value>
      <webElementGuid>3a37dad1-416c-4db8-b859-32cf2c87914e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amtbfgst0</value>
      <webElementGuid>c7a62e67-bcb7-4c0d-a10c-544d52a5249c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>c6c53699-802a-4c6c-b447-c3ca4e7cb61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hr-small-input hr-number number amtbfgst calGSTAmt </value>
      <webElementGuid>91bb8ebe-10c9-4e86-a512-d06f3371c5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>1f12603a-2b96-437d-b55a-13a78f445342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c756d9ee-acc8-4ca1-b349-044059beeacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999999</value>
      <webElementGuid>a0e8edba-13f7-4851-8f12-bd6f74a6506b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amtbfgst0&quot;)</value>
      <webElementGuid>430c8e1f-e2ed-4b9a-a92d-e4e0a970fc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Medical/Page_- Employee Self Service/frame_concat(body bgcolor, , FFFFFF, ,  tex_1268c1</value>
      <webElementGuid>bf4138e8-ddb8-4768-8506-447453636de7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amtbfgst0']</value>
      <webElementGuid>3786e85f-552e-4b1c-8305-df34e2fd0e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trfirst_0']/td[3]/div/input</value>
      <webElementGuid>3b12318c-ff00-4c22-aa1c-07f439d29ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/input</value>
      <webElementGuid>65c2d3ae-85d1-46c2-8627-fff19e71a221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'amtbfgst0' and @id = 'amtbfgst0']</value>
      <webElementGuid>e45fb0fb-38c4-4d91-92ea-7d1edd3489f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
