<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Time Out (24 hours)_timeout0</name>
   <tag></tag>
   <elementGuidId>5bbf74a2-a1fb-49d5-a34a-c16599220138</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#timeout0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='timeout0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32dde480-3894-42d0-b2df-0b822a16352f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f44d9f1-a661-4383-b2df-b4e08defb58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>timeout0</value>
      <webElementGuid>cbd7cbde-f40c-449f-8648-5e7daff13b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timeout0</value>
      <webElementGuid>8e8de39b-0449-406b-8306-37842782efb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hr-time hr-small checkTime24 compare24Time hasDatepicker error</value>
      <webElementGuid>726aa9e0-a5b8-4584-bc17-7fe374b52837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timeout0&quot;)</value>
      <webElementGuid>e95c03c7-3b29-4c94-a8af-e57d23801a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Medical/Page_- Employee Self Service/frame_concat(body bgcolor, , FFFFFF, ,  tex_1268c1</value>
      <webElementGuid>bd213de4-d48d-4e91-b50d-16e88e6eae86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='timeout0']</value>
      <webElementGuid>e044fe87-4e19-4667-bba8-3b426f07b710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trfirst_0']/td/div[3]/input</value>
      <webElementGuid>9fbffd09-729c-4bf9-af8e-d72447d6ed1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>c78e81ca-becf-441c-b71d-7316fc95800d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'timeout0' and @id = 'timeout0']</value>
      <webElementGuid>53bf0f7d-eda1-4119-a4fe-4b45d722c5a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
