<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount Approved (RM)_treatmentdate0</name>
   <tag></tag>
   <elementGuidId>de8c3568-94ca-4a5a-943d-00d258e2812c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#treatmentdate0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='treatmentdate0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa781514-5882-482f-be0f-fffa285fb899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31bca65d-baac-43c4-baa0-620ae9e94aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>treatmentdate0</value>
      <webElementGuid>8dfe076d-fe33-4161-bbf6-725024eb43ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treatmentdate0</value>
      <webElementGuid>ce86a1e7-7ca2-4460-941b-73a3ab512826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hr-date hr-list-date-input populatePatient required checkDateRange checkDateBackdated checkFinancialDate hasDatepicker</value>
      <webElementGuid>0c6f63cd-7818-4016-81b2-0ee9712bd8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treatmentdate0&quot;)</value>
      <webElementGuid>667a57a7-a9a9-4483-bf69-5911790337a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Medical/Page_- Employee Self Service/frame_concat(body bgcolor, , FFFFFF, ,  tex_1268c1</value>
      <webElementGuid>305a0424-e897-41df-970a-5633c7e2ed41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='treatmentdate0']</value>
      <webElementGuid>18c2b262-d97b-4225-bbf9-c753211af022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trfirst_0']/td/div/input</value>
      <webElementGuid>231dcccd-560d-40b7-8792-556d8766aa82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>39e764aa-63c7-4346-b495-11e2a38a584f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'treatmentdate0' and @id = 'treatmentdate0']</value>
      <webElementGuid>c3a1de94-706c-4fc4-9f17-1cbf60ec3a59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
