<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clinic  Hospital Name_sch</name>
   <tag></tag>
   <elementGuidId>644438d5-aa75-4561-a701-56d8a6750070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;sch&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='sch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f76768b-8a4d-4c18-9b8c-37e2e9267c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>649bfadc-274c-4381-a8a9-51a3beed3dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sch</value>
      <webElementGuid>79242871-d178-4eda-971b-437e2d15244b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hr-medium hr-entry-focus</value>
      <webElementGuid>3f729a05-7495-47b8-80d8-811f9c84736e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myformsearch&quot;)/fieldset[@class=&quot;hr-search-form&quot;]/div[@class=&quot;hr-entry-row&quot;]/input[@class=&quot;hr-medium hr-entry-focus&quot;]</value>
      <webElementGuid>a593e479-42b5-4036-a791-4e82e71b6e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Medical/Page_- Employee Self Service/frame_concat(body bgcolor, , FFFFFF, ,  tex_1268c1</value>
      <webElementGuid>9a5821b8-5ff6-461d-9e52-8b5630661a7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='sch']</value>
      <webElementGuid>b5469cfe-8a0d-4774-b717-71a9ac0e4388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='myformsearch']/fieldset/div/input</value>
      <webElementGuid>36b16e66-7413-488e-a057-607b51dbc186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/div/input</value>
      <webElementGuid>1d98907d-77f6-4a20-8fa8-26f0b1b6043b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'sch']</value>
      <webElementGuid>db7a501c-ca2f-40e2-b2f3-603ad77c6df4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
