<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ZAKARIA BIN NAWANI</name>
   <tag></tag>
   <elementGuidId>dd6a77a6-c6f2-418e-9beb-f269af480d48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#patientname0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='patientname0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f5d54357-210a-4c8c-8987-8ddf42ff472b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>patientname0</value>
      <webElementGuid>bdc303b4-76b0-4b2f-bbb1-ed944643f7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>patientname0</value>
      <webElementGuid>3a2d912e-6687-44f4-b698-1582267432a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hr-small-select required calTotalAmount</value>
      <webElementGuid>a25b304c-7350-4fd8-91cf-03989247524d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
ZAKARIA BIN NAWANI</value>
      <webElementGuid>e1eb1ff1-cd7f-4000-832d-ef37daf8a824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patientname0&quot;)</value>
      <webElementGuid>b895a0bd-004e-425e-ac9e-2e66dbceecf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Medical/Page_- Employee Self Service/frame_concat(body bgcolor, , FFFFFF, ,  tex_1268c1</value>
      <webElementGuid>484ba727-9aff-462a-b841-7c0d72918ea1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='patientname0']</value>
      <webElementGuid>caa675cc-d1ae-45ed-9dac-83309d93c910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trfirst_0']/td[2]/div/select</value>
      <webElementGuid>5891a08c-28e0-4c53-afa8-629cd2a7f2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Out (24 hours)'])[1]/following::select[1]</value>
      <webElementGuid>79d4a249-0ba3-4178-bea1-7bae2e24a501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time In (24 hours)'])[1]/following::select[1]</value>
      <webElementGuid>7e1ac130-4a49-4a2c-aa5b-5fe560e1a478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::select[2]</value>
      <webElementGuid>d15c6499-60e7-4c37-bce0-7f42d4112c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Type'])[1]/preceding::select[2]</value>
      <webElementGuid>812ef116-3de6-46fc-bbf3-1d46728d1656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c8118c34-8338-44c9-84c9-7440fc4420e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'patientname0' and @id = 'patientname0' and (text() = ' 
ZAKARIA BIN NAWANI' or . = ' 
ZAKARIA BIN NAWANI')]</value>
      <webElementGuid>f24c3932-87e3-4973-bc86-abd31e5aa9fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
