<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hour_ui-slider-handle ui-corner-all ui_5b7fd8_1</name>
   <tag></tag>
   <elementGuidId>ba8e594c-53c0-470b-8747-995d1c6f80e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ui-slider-handle.ui-corner-all.ui-state-default.ui-state-focus.ui-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui_tpicker_hour_timeout0']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a311e7e5-a352-4d78-b96e-13c14fd1cce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1141105-beb0-4e46-8c96-a64152ca4e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-slider-handle ui-corner-all ui-state-default ui-state-focus ui-state-hover</value>
      <webElementGuid>9fce233d-94c0-448b-b6f6-aa75e6183d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui_tpicker_hour_timeout0&quot;)/span[@class=&quot;ui-slider-handle ui-corner-all ui-state-default ui-state-focus ui-state-hover&quot;]</value>
      <webElementGuid>7486d246-c45a-4294-a36d-2780c92a30c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Medical/Page_- Employee Self Service/frame_concat(body bgcolor, , FFFFFF, ,  tex_1268c1</value>
      <webElementGuid>cb75d944-8b17-4581-b040-556d6247f452</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui_tpicker_hour_timeout0']/span</value>
      <webElementGuid>bb55959b-809e-4f48-9bed-e475bcdcd57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd[2]/div/span</value>
      <webElementGuid>ece86db6-1e62-41e7-8aa7-d36a9352e5e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
