<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Detailed Description_detaildesc0</name>
   <tag></tag>
   <elementGuidId>a884d791-2fba-4932-ab62-3b8097d0f1bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#detaildesc0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='detaildesc0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ea066267-9051-4174-a64f-b160a66d4961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>detaildesc0</value>
      <webElementGuid>e3d7c040-c696-4884-9360-9e9df2e592b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detaildesc0</value>
      <webElementGuid>611f1a73-2a03-4434-9b63-15d0277a5613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>f5cc29c4-e89f-4fbe-b101-54baee35598d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>74025643-4541-4fef-ab91-06b938d156a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>51f4c03c-8903-4415-9abf-a568f6be1108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detaildesc0&quot;)</value>
      <webElementGuid>5cbdb7b2-f2df-495f-9076-aa2de724bcf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Medical/Page_- Employee Self Service/frame_concat(body bgcolor, , FFFFFF, ,  tex_1268c1</value>
      <webElementGuid>9e364206-1111-4be0-9606-3ede557992be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='detaildesc0']</value>
      <webElementGuid>e3e446c0-b678-4a47-9662-05574292bb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trfifth_0']/td[4]/div/textarea</value>
      <webElementGuid>37dd7ffe-5e73-443e-b9f8-fa6d7cbf1d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/textarea</value>
      <webElementGuid>2919861a-311c-4999-970c-5781688357d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'detaildesc0' and @id = 'detaildesc0']</value>
      <webElementGuid>6d025034-450f-4bca-86a2-24098204f374</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
